#!/bin/sh

if [ -f config.status ]; then
	make maintainer-clean
fi

autoreconf -if && \
    ./configure --enable-maintainer-mode \
		--enable-silent-rules \
		--disable-optimization \
		--enable-debug \
		--disable-never-quit \
		--with-log-level=8 \
		--with-log-type=0 $*
